# Generated by Django 5.0.6 on 2024-05-20 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='date_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='превью'),
        ),
    ]
